### ISSUE TITLE
Bottom resizer should not be resizable

### ISSUE THREAD

**Issue by Sixdsn** [Sixdsn/terra-terminal#104]

**Comment by SchnWalter** [comment]
I have a fix for this locally, I have split the UI strings into several `gettext` categories, and while doing that I also updated the `*.ui` with the latest version, and made several small optimizations. I can pull that change out of the i18n commits.

**Comment by Sixdsn** [comment]
Ok great, and yep i rather like to get **ui** files changed out of i18n patches as much as possible

**Comment by Sixdsn** [comment]
@SchnWalter can you push your fix for this? :)

**Comment by SchnWalter** [comment]
I have tested on Gnome and things seem to work.  I have merged the commit because I have a larger batch of changes that could use a review.
