### ISSUE TITLE
Terra terminal window sizing issues

### ISSUE THREAD

**Issue by imammedo** [Sixdsn/terra-terminal#70]
Terra terminal window sizing issues when mouse is used to open a new tab or right-clicked to get context menu on Fedora 21. It's hard to explain so here is screen-cast of how problem looks like  http://youtu.be/2uyc2lb97Xg

**Comment by Sixdsn** [comment]
Hi,

What is your X-server? you had this issue since beginning? on the develop branch?
i don't have a fedora @home so i won't be able to reproduce it.

Thanks,

**Comment by Sixdsn** [comment]
@imammedo Hi can you try to update with the last develop version and tell me if something has changed?
thank you

**Comment by imammedo** [comment]
Issue is still there, although there is a bit of change.
It's the same but less reliable (i.e. maximize window and do right click or  click on net tab button).
Now about changes,
if window is not maximized, clicking on new tab button:
  1 - changes window position, it becomes bigger and jumps to other position.
  2 - and plus original issue but worse, all user area (terminal/tabs) is hidden after #1 and resized window is occupied by not interactive gray or transparent area. I have to resize window using right lower corner to the top left and back to get back tabs and terminal.
1. \- sometimes right click doesn't cause issues but new tab button does it reliably.

**Comment by Sixdsn** [comment]
Hi @imammedo,

We did a lot af changes that might fix some part of your issues (i would guess all issues but...)
Can you launch terra in a terminal to see if there are some debug or error messages when it happens?
do a git pull on the develop branch and sudo ./setup install to get it updated

Thanks,

**Comment by imammedo** [comment]
I've just updated to the latest devel branch and upgraded to fedora 22 at the same time.
most of issues are resolved. Thanks for fixing the most of issues.

There is a small issue left, but it might deserve it own issue #.
On dual display system with vertical oriented left display and horizontal oriented on right,
1. open the first terminal window and it's created on right (main) display
2. then I create second terminal window and move it to the left display
3. click on 'new tab' button in the left terminal window
   Result:
   new tab is created and left window jumps to the right display and becomes maximized.
   Expected:
   new tab is created and left window stays at the same position/same size.

**Comment by Sixdsn** [comment]
@imammedo : i tested it and it should finnaly be fixed ;)
can you confirm you don't have that issue anymore?

Thanks,

**Comment by imammedo** [comment]
I've just updated and it works for me too.

Thanks for fixing it!

**Comment by Sixdsn** [comment]
Thanks for your feedback :)
