### ISSUE TITLE
wrong path in terra_0.2.0_amd64.deb

### ISSUE THREAD

**Issue by muzena** [Sixdsn/terra-terminal#71]
When i build from develop repository   debuild -us -uc -B, and install terra.
terra wont start.
In terra.desktop file is wrong path, Icon=/home/mint/terra/terra-terminal/debian/terra/usr/share/terra/image/terra.svg
In file /usr/lib/python2.7/dist-packages/terra/config.py, 27 line __terra_data_directory__ = '/home/mint/terra/terra-terminal/debian/terra/usr/share/terra/':

**Comment by Sixdsn** [comment]
Hi,

Thanks for the report, this last commit fixed it on my system ;)

**Comment by Sixdsn** [comment]
@muzena can you give me a feedback, i fully tested it this weekend and it looks ok.
Thanks,

**Comment by SchnWalter** [comment]
@muzena could you maybe test with PR https://github.com/Sixdsn/terra-terminal/pull/78, that branch is using a different way to build the project, and we no longer have hard-coded paths in the project.

But I don't have a Debian based system available for testing.

**Comment by Sixdsn** [comment]
Well actually something goes wrong...
When building with debuild we anly have a empty package which doesn't contain any binary anymore

**Comment by SchnWalter** [comment]
I've looked into setup.py to integrate i18n, I've got it working now.  I only need to figure out the directory structure... and then I can look also into generating deb packages from the project.  I know setup.py can be used for generating many types of distribution packages but not `.deb` packages.

**Comment by muzena** [comment]
@SchnWalter 
I try to build, but in deb file is only doc folder, changelog.gz and copyright file in /usr/share/doc/terra/ path

**Comment by Sixdsn** [comment]
Hi,

I opened a new issue corresponding to the actual issue #105.
This one is 'fixed' but now we need to figoure out the whole build issue
