### ISSUE TITLE
libvte: 'fork_command_full' moved to  'vte_terminal_spawn_sync ()'

### ISSUE THREAD

**Issue by Sixdsn** [Sixdsn/terra-terminal#75]
From issue #63:
hyperion@linux:/workspace/dev/terra-terminal> terra
Exception Catched:
'Terminal' object has no attribute 'fork_command_full'

Since libvte 0.38,'fork_command_full' is replaced by 'vte_terminal_spawn_sync ()'

**Comment by Sixdsn** [comment]
It looks like this issue was already fixed since the code is

```
        if hasattr(self.vte, 'fork_command_full'):
            fork = self.vte.fork_command_full
        elif hasattr(self.vte, 'spawn_sync'):
            fork = self.vte.spawn_sync
    else:
            raise Exception('no symbols in libVte to fork program')
```

@SchnWalter: Did you checked out the develop branch?

**Comment by SchnWalter** [comment]
Ups..., i'm using the default branch (master) :D
