### ISSUE TITLE
Push code upstream

### ISSUE THREAD

**Issue by SchnWalter** [Sixdsn/terra-terminal#76]
Have you tried contacting @ozcanesen in order to push changes upstream?

I see that he did not respond on issue #58

**Comment by Sixdsn** [comment]
I think he isn't working anymore on this.
the repo on github isn't updated anymore since he moved to launchpad: https://launchpad.net/terra
which hasn't been updated since two years

**Comment by SchnWalter** [comment]
In the mean time could we maybe have the "develop" as the main branch? It will be easier to work with the GitHub UI.

**Comment by Sixdsn** [comment]
The default branch is now develop ;)

**Comment by SchnWalter** [comment]
Thanks ;)
