### ISSUE TITLE
Update labels

### ISSUE THREAD

**Issue by SchnWalter** [Sixdsn/terra-terminal#85]
Could we maybe also have these two labels: `in progress` and `awaiting review`

And maybe we could also change some of the colors, we don't need the "Backend", "GUI", "Installer" and "Wiki" labels to have such intense colors, we should reserve those for things like "bug", "Tests-needed" or "awaiting review".

UPDATE:
And maybe have these "component" specific tags ("Backend", "GUI", "Installer" and "Wiki") all in the same color.

**Comment by Sixdsn** [comment]
I'm kinda color blind so have fun with the label colors :)
agree to add the two labels and a `blocked` labels which means this can't be fixed until another issue is fixed

**Comment by Sixdsn** [comment]
Done ;)
