### ISSUE TITLE
not well caught exception during launch

### ISSUE THREAD

**Issue by visheyra** [Sixdsn/terra-terminal#97]
branch -> develop
last commit ->

```
commit 6bd46c69461554603f1663a7aeabe7e09d947d76
Merge: ace52ae d491d43
Author: Six <six.dsn@gmail.com>
Date:   Mon Jun 29 10:35:18 2015 +0200

Merge pull request #94 from Sixdsn/feature/interfaces-submodule

Interfaces submodule
```

Problem:
Sometimes on startup an exception is caught then a traceback append

```
Exception: NULL result without error in PyObject_Call
Traceback (most recent call last):
  File "/usr/bin/terra", line 9, in <module>
    load_entry_point('terra==0.3.0', 'console_scripts', 'terra')()
  File "/usr/lib/python2.7/site-packages/terra-0.3.0-py2.7-linux-x86_64.egg/terra/__main__.py", line 64, in main
    TerraHandler.Wins.app_quit()
AttributeError: 'NoneType' object has no attribute 'app_quit'
```

System -> Archlinux
Python -> Python 2.7.10
Installation -> installed as a standard program by sudo (sudo python2 setup.py install)

**Comment by SchnWalter** [comment]
@Sixdsn are you OK with removing the try-except from `__main__.py`?

I would rather have it crash and display all the errors. For example on this case, probably `TerminalWinContainer.__init__()` threw this error since `TerraHandler.Wins` is still None.

**Comment by Sixdsn** [comment]
Well I don't like when a program crashes that way but actually it's not weird and helps us to get more intel to debug and actually when i'm debugging i remove this try catch so i guess it's okay to remove it ;)

**Comment by SchnWalter** [comment]
@sin66617 could you please test again and let us know the full error that you see?  I've just tested the application on ArchLinux this weekend, and it seems to work for me.  You might not have all dependencies installed.

**Comment by visheyra** [comment]
Effectively there's no more crash during the launch :+1:

**Comment by Sixdsn** [comment]
Ty @sin66617  :)
